version: '3.8'

networks:
  bmn-ms-network:

volumes:
  app-data:

services:
  webserver-campaign-service:
    image: nginx:1.21.6-alpine
    container_name: webserver-campaign-service
    restart: unless-stopped
    ports:
      - "8071:80"
    volumes:
      - ./:/var/www
      - .docker/nginx:/etc/nginx/conf.d
    networks:
      bmn-ms-network:

  backend-campaign-service:
    build:
      context: .docker/php
      dockerfile: dockerfile
    container_name: backend-campaign-service
    volumes:
      - ./:/var/www
      - .docker/php/php.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      bmn-ms-network: